on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      
#       - run: |
#           git fetch --prune --unshallow --tags
#       - name: Install commitzen
#         run: |
#             pip install -U commitizen
#             cz version
#       - name: Create changelog
#         run: |
#             git tag 
#             git config --global user.email "skiyl9x@gmail.com"
#             git config --global user.name "Alex"
#             cz bump --yes --changelog
#       - name: Changelog
#         uses: Bullrich/generate-release-changelog@master
#         id: Changelog
#         env:
#           REPO: ${{ github.repository }}
          
#       - name: release
#         uses: actions/create-release@v1
#         id: create_release
#         with:
#           draft: false
#           prerelease: false
#           release_name: v1.0.4
#           tag_name: v1.0.4
#           body: |
#             ${{ steps.Changelog.outputs.changelog }}
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#
          
#       - uses: google-github-actions/release-please-action@v3
#         with:
#           release-type: simple
#           package-name: release-please-action

#       - uses: snyk/release-notes-preview@v1.6.1
#         with:
#           releaseBranch: main
#         env:
#           GITHUB_PR_USERNAME: ${{ github.actor }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# #

#       - name: Release create
#         run: | 
#             echo ${{ secrets.GITHUB_TOKEN }} > .githubtoken
#             gh auth login --with-token < .githubtoken
#             rm -f .githubtoken
#             git push --tags
#             git push
#             version=$(cat .cz.toml  | tail -1 | awk -F "=" '{print $2}' |  sed 's/"//g')   
#             gh release create $version -F ./CHANGELOG.md
            
            
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            body_path: "body.md"
            tag_name: ${{ env.REVISION }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
